config/routes.rb
Rails.application.routes.draw do
  get 'rents/index'
  resources :books do
    member do
      get 'rental'
    end
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :users

  def rental(user)
    Rent.create(book: self, user: user)
  end

end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  # パラメータキー（ユーザコード）
  PARAMSKEY_USER_CODE = "user_code"

  private

  def require_login
    unless logged_in?
      session[:current_user_code] = params[PARAMSKEY_USER_CODE] if Rails.env.development?
      session[:current_user_code] ||= request.headers[:HTTP_USER_CODE]
      @current_user = User.find_by(user_code: session[:current_user_code])
      # ユーザが存在しない場合は消す
      if @current_user.nil?
        session[:current_user_code] = nil
      end
    end
  end

  def logged_in?
    ret = (session[:current_user_code] == params[PARAMSKEY_USER_CODE]) if Rails.env.development?
    ret &&= (session[:current_user_code] == request.headers[:HTTP_USER_CODE])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy rental ]

  # GET /books or /books.json
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.page(params[:page]).per(5)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /books/1/rental
  def rental
    if rent = @book.rental(@current_user)
      render json: [ Rent: rent ] , status: 200
    else
      render json: [ ] , status: 500
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name)
    end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    @rents = Rent.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_code, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.slim
= form_with(model: book) do |form|
  - if book.errors.any?
    #error_explanation

    h2
      = pluralize(book.errors.count, "error")
      |  prohibited this book from being saved:
    ul
      - book.errors.each do |error|
        li
          = error.full_message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/books/edit.html.slim
h1
  | Editing Book
= render 'form', book: @book
= link_to 'Show', @book
|  | 
= link_to 'Back', books_path

app/views/books/index.html.slim
p#notice
  = notice
h1
  | Books

= search_form_for(@q) do |f|
  p
    = f.label :name_cont, '名前'
    = f.search_field :name_cont
  = f.submit

= paginate @books

table
  thead
    tr
      th
        | Name
      th[colspan="3"]
  tbody
    - @books.each do |book|
      tr
        td
          = book.name
        td
          = link_to 'Show', book
        td
          = link_to 'Edit', edit_book_path(book)
        td
          = link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Book', new_book_path

app/views/books/new.html.slim
h1
  | New Book
= render 'form', book: @book
= link_to 'Back', books_path

app/views/books/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @book.name
= link_to '借りる', rental_book_path(@book), data: { confirm: '借りますか？' }, method: :get, :class => 'btn btn-primary rental_button', remote: true
|  | 
= link_to 'Edit', edit_book_path(@book)
|  | 
= link_to 'Back', books_path

javascript:
  $('.rental_button').on('ajax:success', function(event) {
    alert('借りれました！')
  }).on('ajax:error', function(event) {
    alert('エラーが起きたので借りれませんでした')
  })

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsTutorial
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render template:'layouts/header'
    main
      .container
        = yield
    = render template:'layouts/footer'

app/views/layouts/footer.slim
footer
  .container 
    .d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top
      .col-md-4.d-flex.align-items-center
      .col-md-4.justify-content-end.list-unstyled.d-flex
        = "© 2021 Company, Inc"

app/views/layouts/header.slim
header
  .container
    .d-flex.flex-wrap.justify-content-center.py-3.mb-4.border-bottom
      = link_to("/", {class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"})
        span.fs-4
          = "TITLE"
      ul.nav.nav-pills
        li.nav-item
          = link_to("Home", "#", {class: "nav-link active"})
        li.nav-item
          = link_to("Features", "#", {class: "nav-link"})
        li.nav-item
          = link_to("Pricing", "#", {class: "nav-link"})
        li.nav-item
          = link_to("FAQs", "#", {class: "nav-link"})
        li.nav-item
          = link_to("About", "#", {class: "nav-link"})
        li.nav-item 
          = link_to(@current_user.try(:name), "#", {class: "nav-link"})

app/views/rents/index.html.slim
p#notice
  = notice
h1
  | Rents

table
  thead
    tr
      th
        | User
      th
        | Book
      th
        | Rent DateTime
  tbody
    - @rents.each do |rent|
      tr
        td
          = rent.user.name
        td
          = rent.book.name
        td
          = rent.created_at

app/views/users/_form.html.slim
= form_with(model: user) do |form|
  - if user.errors.any?
    #error_explanation

    h2
      = pluralize(user.errors.count, "error")
      |  prohibited this user from being saved:
    ul
      - user.errors.each do |error|
        li
          = error.full_message
  .field
    = form.label :user_code
    = form.text_field :user_code
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Users
table
  thead
    tr
      th
        | User code
      th
        | Name
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.user_code
        td
          = user.name
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
p
  strong
    | User code:
  = @user.user_code
p
  strong
    | Name:
  = @user.name
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path